name: Build Application

on : [push]

jobs:
    install:
        name: Installing Packages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache node_modules
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ hashFiles('**/package-lock') }}

            - name: Install dependencies
              run: npm install

    UnUsedExport:
        name: Unused export module
        runs-on: ubuntu-latest
        needs: install
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Restore node_modules
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ hashFiles('**/package-lock') }}

            - name: Run ts-prune
              run: npx ts-prune --error

    lint:
      name: Run eslint
      runs-on: ubuntu-latest
      needs: UnUsedExport
      steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Restore node_modules
            uses: actions/cache@v3
            with:
              path: node_modules
              key: ${{ runner.os }}-${{ hashFiles('**/package-lock') }}

          - name: Run eslint
            run: npm run lint


    testing:
        name: Run test
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Restore node_modules
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ hashFiles('**/package-lock') }}

            - name: Run vitest
              run: npm run test
                